name: Build and deploy ASP.Net Core app to Azure Web App - pledger-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SOLUTION_FILE: [project-ledger-api.sln](http://_vscodecontentref_/0)
  PROJECT_FILE: [ProjectLedger.API.csproj](http://_vscodecontentref_/1)
  PUBLISH_DIR: ./publish

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_FILE }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ${{ env.PROJECT_FILE }} --configuration Release --no-build --output ${{ env.PUBLISH_DIR }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: net-app
          path: ${{ env.PUBLISH_DIR }}

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: net-app
          path: ./artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_925460EFAB144D2A9C100C22FB766928 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E033666BD9F046C792201692B844BC61 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AA76DB8F78274C51964B2EF5778F66A9 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: pledger-api
          slot-name: Production
          package: ./artifact
